fix: Fixed rendering error when the root node contains dynamic content
vuejs/core-vapor pull request #1
Opened 2023-11-24 09:17 UTC by baiwusanyu-c

Handled errors in some use cases.

```
<template>
  <button @click="handleClick" :id="count">
   {{count}}
  </button>
</template>
```

```
<template>
  <button @click="handleClick" :id="count">
    foo {{count}}
  </button>
</template>
```

```
<template>
  <button @click="handleClick" :id="count">
    foo {{count}} foo
  </button>
</template>
```

2023-11-24 09:18 UTC, autofix-troubleshooter commented
Hi! I'm the <a href="https://autofix.ci"><img alt="autofix logo" src="https://autofix.ci/logo/logo.svg" width="16"><strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

2023-11-24 12:29 UTC, sxzz requested changes
This problem is resolved via 91e7f9bb835936f8b0f8edf5750c9bedeb0cf8c5

But the unit tested is still needed

2023-11-24 12:29 UTC, sxzz commented on packages/compiler-vapor/__tests__/basic.test.ts
> +import singleRootSource from './fixtures/singleRoot.vue?raw'
The fixtures test is for dev only. Please add unit test separately.
See https://github.com/vuejs/core-vapor/blob/acec2409c7694c5dd37a3f173fe432899549866e/packages/compiler-vapor/__tests__/compile.test.ts

2023-11-27 15:19 UTC, sxzz reviewed
Please remove empty file `packages/compiler-vapor/__tests__/__snapshots__/basic.test.ts.snap`

2023-11-27 15:19 UTC, sxzz commented on packages/compiler-vapor/__tests__/compile.test.ts
> +  test('Dynamic root nodes and interpolation', async () => {
```suggestion
  test('dynamic root nodes and interpolation', async () => {
```

2023-11-28 05:06 UTC, sxzz approved these changes

2023-11-28 05:06 UTC, merged