feat(compiler-vapor): complex Identifier rewriting with vOn
vuejs/core-vapor pull request #113
Opened 2024-02-02 16:26 UTC by LittleSound

the examples

```vue
<div @click="x=y"/>
<div @click="x++"/>
<div @click="{ x } = y"/>
```

2024-02-04 13:00 UTC, sxzz requested changes
Case: https://deploy-preview-113--vapor-template-explorer.netlify.app/#eyJzcmMiOiI8ZGl2IDpmb289XCJ7IHNldHVwUmVmIH1cIiBAY2xpY2s9XCJ7IHg6IHNldHVwUmVmIH0gPSAkZXZlbnRcIj48L2Rpdj4iLCJvcHRpb25zIjp7fX0=

2024-02-05 13:22 UTC, LittleSound commented
> ```diff
> --- _on(n1, "click", $event => ({ x: setupRef: _ctx.setupRef } = $event))
> +++ _on(n1, "click", $event => ({ x: _ctx.setupRef } = $event))
> --- _setDynamicProp(n1, "foo", { _ctx.setupRef })
> +++ _setDynamicProp(n1, "foo", { setupRef: _ctx.setupRef })
> ```

Fixed this case

2024-02-05 14:36 UTC, sxzz commented
Tweaked about source map. Merged!

2024-02-05 14:36 UTC, sxzz approved these changes

2024-02-05 14:37 UTC, merged