feat(vapor-runtime): object support in `v-for`
vuejs/core-vapor pull request #139
Opened 2024-02-27 09:47 UTC by wangyewei

add support for object iteration in v-for

2024-02-27 11:49 UTC, sxzz requested changes
Conflicts need to be resolved

2024-02-27 15:38 UTC, sxzz commented on packages/runtime-vapor/src/for.ts
> +          const keys = Object.keys(source)
Can we reuse `keys`?

2024-02-27 15:38 UTC, sxzz commented on packages/runtime-vapor/src/for.ts
>    const mountList = (source: any[], offset = 0) => {
`source` could be Record

2024-02-29 22:35 UTC, closed without merging

2024-02-29 22:39 UTC, sxzz commented
Thanks for your contribution. Implemented via 4af8e879 which combined with your commit.

2024-03-04 21:44 UTC, septatrix commented
I assume the readme should also be updated?

https://github.com/vuejs/core-vapor/blob/d3ca3f7492cbd685aef934acd8dadc8069829930/README.md?plain=1#L47-L49

2024-03-05 09:56 UTC, sxzz commented
Thanks for your reminder. Updated!