feat: support v-on="obj"
vuejs/core-vapor pull request #149
Opened 2024-03-13 06:59 UTC by Jevon617

2024-03-13 08:41 UTC, sxzz requested changes
We should avoid introducing the `setDynamicEvents` function and instead reuse `setDynamicProps` to support the following code:

```vue
<button v-bind="{ onClick: fn }" />
<button v-on="{ click: fn }" />
```

Both approaches are equivalent.

2024-03-13 08:41 UTC, sxzz commented on packages/compiler-vapor/src/ir.ts
> +  prop: SimpleExpressionNode
```suggestion
  event: SimpleExpressionNode
```

2024-03-13 08:46 UTC, sxzz requested changes
Should also emit an error, if no `modifiers` or no `arg`

```vue
<button v-on.prevent />
```

2024-03-14 02:14 UTC, Jevon617 commented
> Should also emit an error, if no `modifiers` or no `arg`
> 
> ```
> <button v-on.prevent />
> ```

Are you saying that this situation should emit an error?
```
<button v-on.prevent="{}" />
```

2024-03-14 06:15 UTC, merged

2024-03-14 06:22 UTC, Jevon617 commented
I will replace `setDynamicEvents` with `setDynamicProps` through the next pr, and add some test cases.