fix(runtime-vapor): detach effect scope & component instance
vuejs/core-vapor pull request #174
Opened 2024-04-05 13:21 UTC by LittleSound

The existing `setCurrentInstance` will set `instance.scope.on()` internally and `instance.scope.off()` when calling reset, but as an internal Function, this hidden behavior is not very intuitive, and there are two problems:

1. `effectScope.on` cannot handle nested recursive calls to itself, because the internal `prevScope` can only store one value.
2. Not all situations that need to set `currentInstance` need to set `instance.scope.on()` at the same time, and this behavior is wrong in `renderEffect`.

So this PR removes `instance.scope.on()` in `setCurrentInstance`.

I initially started investigating this issue because of the following bug.

[Bug Playground](https://vapor-repl.netlify.app/#__VAPOR__eNp9UcFu1DAQ/ZWROXhX2iaq4LRKgwD1AAdAgLhgDiGZJC6ObdlOWBTl3xk77DatqkaKZL/3ZvzmzczeWJtNI7IjK3ztpA3gMYy2FFoO1rgAMzhsYYHWmQE4SbnQtdE+wOA7uInsjveolOF7oYt87UL1dAk4WFUFpBtAIbUdA0xXg2lQ3QhG9YJBvpLxRaDvR+FtpUnVGkea3XSQezBtfEywsvhVzjNMsCxFno4SikhlCnUX+qtreA38wI+cJ0lsVf5M/fP1gaK/pjKqiDSdo+ONS3ZgUjd4yvowqE0m4a/F6Ng0o0LysXqN3yWl2iH1+F7RlTLdBpZPEaTYHtVE2SrK8v9r2Ige9tvRv88GM+qw4y8qa/n+EnXRyAlkQ/4IjyHlBJQ0SvC0qFZ22Z03mqaZY3fBajNYqdB9skHSIgU7QmIiV9Ee/3xIWHAjHs543WP9+wn8zp8iJthnhx7dROFcuFC5DsNK3379iCc6X8hzlM+QX9AbNUaPq+ztqBuyvdElt+9TmlJ33/ztKaD256Gi0ahckl4wyvfdM6Pf232ZvUp1Qi9s+QeIPARv)

In this example, try entering text.

There won't be any problem if just adding texts, once the the pe-existing texts get deleted, it will cause the call to`setText` to fail.
This is because when the `v-for` element get unmounted, the `effect.onStop()` that does not belong to the `v-for` element would be mistakenly called. This is caused by the combined problems with problem "1" and "2" mentioned above.

2024-04-05 15:23 UTC, sxzz approved these changes

2024-04-12 19:26 UTC, sxzz requested changes
LGTM. But could you please add unit tests for it?

2024-04-12 19:26 UTC, sxzz commented on packages/runtime-vapor/src/componentLifecycle.ts
> +        instance.scope.run(() => {
```suggestion
        instance.scope.run(() =>
```

2024-04-12 19:26 UTC, sxzz commented on packages/runtime-vapor/src/componentProps.ts
> +        instance.scope.run(() => {
```suggestion
        instance.scope.run(() =>
```

2024-04-15 13:56 UTC, LittleSound commented
Added unit tests to the critical path that triggered the bug.

2024-04-16 08:54 UTC, sxzz approved these changes

2024-04-16 08:55 UTC, merged