feat: v-once support for v-if/else via a once flag
vuejs/core-vapor pull request #200
Opened 2024-05-06 09:26 UTC by lulu0119

Implemented basic v-once support for v-if/else via a **once** flag, please review and advise if any scenarios are unaddressed.

2024-05-06 09:45 UTC, LittleSound requested changes

2024-05-06 09:45 UTC, LittleSound commented on packages/runtime-vapor/src/apiCreateIf.ts
> +  once?: Boolean,
```suggestion
  once?: boolean,
```

2024-05-06 09:45 UTC, LittleSound commented on packages/compiler-vapor/src/generators/if.ts
> +      once ? String(once) : '',
```suggestion
      once && 'true',
```

2024-05-06 12:49 UTC, lulu0119 commented
Thank you, sxzz, for helping me with the modifications.

2024-05-07 11:12 UTC, LittleSound approved these changes

2024-05-12 10:17 UTC, sxzz approved these changes

2024-05-12 10:18 UTC, sxzz commented on packages/compiler-vapor/src/generators/if.ts
> +      negativeArg || (once ? 'null' : false),
Should add a placeholder if once is true but no negative branch.

2024-05-12 10:20 UTC, merged