test(runtime): globalProperty
vuejs/core-vapor pull request #255
Opened 2024-06-24 07:41 UTC by GaoNeng-wWw

2024-06-24 10:54 UTC, LittleSound approved these changes

2024-06-25 02:06 UTC, xiaodong2008 requested changes

2024-06-25 02:06 UTC, xiaodong2008 commented on packages/runtime-vapor/__tests__/apiCreateVaporApp.spec.ts
> +    expect(host.innerHTML).toBe('hello world')
Use `html()` instead of `host.innerHTML`

2024-06-25 02:06 UTC, xiaodong2008 commented on packages/runtime-vapor/__tests__/apiCreateVaporApp.spec.ts
> +    const { app, mount, host } = define({
Use `html` instead of `host`

2024-06-25 02:37 UTC, xiaodong2008 approved these changes

2024-06-25 04:26 UTC, LittleSound approved these changes

2024-07-14 17:09 UTC, sxzz approved these changes

2024-07-14 17:10 UTC, merged